# Generated by Django 6.0 on 2026-05-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_checkout_request_id_payment_mpesa_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_receipt',
        ),
    ]
